/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import dominio.Ficha;
import dominio.Jugador;
import dominio.Partida;
import dominio.Sistema;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;

/**
 *
 * @author Caro
 */
public class ReplicarPartida extends javax.swing.JFrame {
    
    private Sistema sistema;
    private Ficha[][] tablero;
    private Jugador jugador1;
    private Jugador jugador2;
    private Jugador turno;
    private int contadorTurno = 0;
    private String fichaAnterior = "";

    /**
     * Creates new form ReplicarPartida
     */
    public ReplicarPartida() {
        initComponents();
    }
    
    public ReplicarPartida(java.awt.Frame parent, boolean modal, Sistema sis) {
        initComponents();
        sistema = sis;
        //sistema.registrarJugador(new Jugador("as","as",55));
        
        DefaultComboBoxModel opcion = new DefaultComboBoxModel();
        
        try {
            if (sistema.getPartidas().size() > 0) {
                for (Partida partida : sistema.getPartidas()) {
                    opcion.addElement(partida);
                }
                cmbPartidas.setModel(opcion);
                cmbPartidas.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        this.setSize(new Dimension(600, 600));
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        //this.modelo = sistema;
        jugador1 = sistema.getJugador1();
        jugador2 = sistema.getJugador2();
        turno = jugador1;
        lbljug.setText(turno.getAlias());
        tablero = sistema.getTablero().getTablero();      
        //Tamaño por defecto de la ventana (JFrame) al abrirlo
        this.setSize(new Dimension(600, 600));
        
        panelRepPartida.setLayout(new GridLayout(8, 9));
        int largo = tablero[0].length - 1;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 9; j++) {
                JButton jButton = new JButton();
                jButton.addActionListener(new ReplicarPartida.ListenerBotonRep(i, j));
                Ficha ficha = new Ficha(" ", " ", jButton);
                if (i == 0) {
                    if (j != 0) {
                        ficha = new Ficha(String.valueOf(j), "AZUL", jugador2, jButton);                 
                        tablero[i][j] = ficha;
                    } else {                         
                        tablero[i][j] = ficha;
                    }
                } else if (i == tablero.length - 1) {
                    if (j != tablero[0].length - 1) {
                        ficha = new Ficha(String.valueOf(largo--), "ROJO", jugador1, jButton);                      
                        tablero[i][j] = ficha;
                    } else {
                        tablero[i][j] = ficha;
                    }
                } else {
                    tablero[i][j] = ficha;
                }
                ficha.getBoton().setForeground(Color.WHITE);
                ficha.getBoton().setText(ficha.getNro());                
                switch(ficha.getColor()) {
                    case "ROJO":
                        jButton.setBackground(Color.RED);
                        break;
                    case "AZUL":
                        jButton.setBackground(Color.BLUE);
                        break;
                    default:
                        jButton.setBackground(Color.WHITE);
                        break;
                }                
                panelRepPartida.add(ficha.getBoton());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRepPartida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbljug = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbPartidas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelRepPartida.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelRepPartidaLayout = new javax.swing.GroupLayout(panelRepPartida);
        panelRepPartida.setLayout(panelRepPartidaLayout);
        panelRepPartidaLayout.setHorizontalGroup(
            panelRepPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        panelRepPartidaLayout.setVerticalGroup(
            panelRepPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(panelRepPartida);
        panelRepPartida.setBounds(90, 70, 450, 450);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Turno de: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 80, 30);

        lbljug.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lbljug);
        lbljug.setBounds(470, 20, 70, 30);

        jButton1.setText("Siguiente movimiento");
        jButton1.setActionCommand("");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 540, 210, 40);

        jButton2.setText("Retomar partida");
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 540, 220, 40);

        cmbPartidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbPartidas);
        cmbPartidas.setBounds(90, 20, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplicarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplicarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplicarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplicarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RepetirPartida dialog = new RepetirPartida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPartidas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbljug;
    private javax.swing.JPanel panelRepPartida;
    // End of variables declaration//GEN-END:variables

    private class ListenerBotonRep implements ActionListener {

        private int x;
        private int y;

        public ListenerBotonRep(int i, int j) {
            // en el constructor se almacena la fila y columna que se presionó
            x = i;
            y = j;
        }

        public void actionPerformed(ActionEvent e) {
            // cuando se presiona un botón, se ejecutará este método
            clickBoton(x, y);
        }
    }

    private void clickBoton(int fila, int columna) {        
        if ((fila + "" + columna).equals(fichaAnterior)) {
            
            JOptionPane.showMessageDialog(this, fila + "/" + columna + "igual");
        } else {
            JOptionPane.showMessageDialog(this, fila + "/" + columna + "dif");
        }
        fichaAnterior = fila + "" + columna;
    }
    
    private void marcarPosiblesMovimientos (int fila, int columna) {
        //if (fila == 0)
        
    }
}
